name: spirv-tools
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: SPIR-V Tools project provides an API & commands for processing SPIR-V modules.
description: |
  The project includes an assembler, binary module parser, disassembler, validator, and optimizer for SPIR-V.
  Except for the optimizer, all are based on a common static library. The library contains all of the implementation
  details, and is used in the standalone tools whilst also enabling integration into other code bases directly.
  The optimizer implementation resides in its own library, which depends on the core library.
  The interfaces have stabilized. We don't anticipate making a breaking change for existing features.
  SPIR-V is defined by the Khronos Group Inc. See the SPIR-V Registry for the SPIR-V specification, headers,
  and XML registry.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  spirv-as:
    command: spirv-as
  spirv-cfg:
    command: spirv-cfg
  spirv-dis:
    command: spirv-dis
  spirv-link:
    command: spirv-link
  spirv-markv:
    command: spirv-markv
  spirv-opt:
    command: spirv-opt
  spirv-stats:
    command: spirv-stats
  spirv-val:
    command: spirv-val

parts:
  spirv-tools:
    plugin: dump
    source-type: zip
    source: https://github.com/KhronosGroup/SPIRV-Tools/releases/download/master-tot/SPIRV-Tools-master-linux-RelWithDebInfo.zip
